sudo: false
language: node_js
node_js:
  - node
  - 'lts/*'
install:
  - npm install -g codecov
script:
  - npm run coverage
after_success:
  - npm run test
  - npm run coverage
notifications:
  email: false